### ISSUE TITLE
Cache Folder

### ISSUE THREAD

**Issue by pschuchmann** [FriendsOfREDAXO/osmproxy#12]
Hey,

mir ist aufgefallen, dass das Addon aktuell ziemlich viel Benachrichtigungen im System Log produziert. So wie es aussieht, liegt das am Umzug des Folders in dem die Tiles gespeichert werden. Der Cache Ordner wird aktuell nur beim Installieren angelegt, wird der Cache aber gelöscht, wird auch dieser Ordner gelöscht und danach nie wieder neu erstellt und die Tiles können nicht darin abgelegt werden.

**Comment by skerbis** [comment]
sollte erledigt sein
