### ISSUE TITLE
Fehler beim Abruf auf manchen Servern

### ISSUE THREAD

**Issue by iceman-fx** [FriendsOfREDAXO/osmproxy#13]
Bei manchen Hostern wirft der curl-Abruf einen Zertifikatsfehler, obwohl das Zertifikat nicht abgelaufen ist und korrekt funktioniert.

Curl-Fehler: SSL certificate problem: certificate has expired

**Comment by skerbis** [comment]
Sorry. Das ist ein Problem von curl denke ich nicht vom AddOn an sich

**Comment by iceman-fx** [comment]
Ich habe dazu einen PR aufgemacht.
