### ISSUE TITLE
Update löscht das data-Verzeichnis

### ISSUE THREAD

**Issue by christophboecker** [FriendsOfREDAXO/osmproxy#4]
Moin,

ich bin auf Probleme mit dan Data-Verzeichnis gestoßen. Endlose fehlermeldungen im Log, dass die Datei xx_yyyy_zzzz.png nicht angelegt werden kann (und dazu ein Haufen Folgefehler). Gund der Ursache: das Verzeichnis "redaxo/data/addons/osmproxy" fehlt. gegenprobe: Verzeichnis angelegt und es lief wirder wie erwartet. 

Wahrscheinlich bei einem Update verloren gegangen, denn in der update.php finde ich: 'rex_dir::delete($this->getDataPath());', was darauf schließen lässt, dass die update.php eine Kopie der uninstall.php ist.

Das bringt mich zu zwei Sachen:

**install.php**
Ich verstehe nicht, warum erst das osmproxy-Verzeichnis unter data gelöscht und dann das aus dem Addon (mit einer Datei) nach data kopiert wird? Reicht es nicht, das Verzeichnis unter Data anzulegen?

**uninstall.php**
entweder löschen oder (sicher ist sicher) das Verzeicnis unter data anlegen.
'rex_dir:.create($this->getDataPath();'

**Comment by skerbis** [comment]
@christophboecker danke für die Info. Bitte aktuelle GitHub-Version testen.

**Comment by christophboecker** [comment]
Ok, zwei Anmerkungen:
1) mein Issue ist fehlerhaft formuliert: nicht uninstall.php, sondern update.php ist das Problem und sollte raus. Denn update.php löscht das data-Verzeichnis; danach funktioniert osmproxy nicht mehr.

2) ich hab noch mal rumprobiert: auch uninstall.php kann ersatzlos gestrichen werden, denn die Addon-Verwaltung löscht auch data-Verzeichnisse automatisch beim Deinstallieren.

**Comment by staabm** [comment]
Stimmt vermutlich. Ich glaube der core räumt diese dinge auf.

Das data verzeichnis bleibt aber zwischen updates erhalten, soweit ich mich erinnere

**Comment by skerbis** [comment]
Die update.php löscht jetzt nur die Dateien, ist das für Dich ok? Es gibt die update.php weil in einer frühen Version die Dateien anders benannt waren und es probleme mit dem Cache gab. Sicher, eigentlich kann sie wohl wieder weg. Bitte testen. Ich bringe dann ein neues Release.

**Comment by christophboecker** [comment]
Soweit testbar ok. Danke.

**Comment by skerbis** [comment]
im aktuellem Release gelöst - danke @christophboecker
