### ISSUE TITLE
neue Url beim deutschen Server 

### ISSUE THREAD

**Issue by tbaddade** [FriendsOfREDAXO/osmproxy#6]
Verwendet man den deutschen Server, kann es passieren das die Fliesen nicht mehr geladen werden.

**Alt:**
`https://c.tile.openstreetmap.de/tiles/osmde/18/137376/88760.png`

**Neu:**
`https://c.tile.openstreetmap.de/18/137376/88760.png`

Um dies vorzubeugen, sollte bei Curl zusätzlich die Option `FOLLOWLOCATION` gesetzt werden.

**Comment by tbaddade** [comment]
> Um dies vorzubeugen, sollte bei Curl zusätzlich die Option FOLLOWLOCATION gesetzt werden.

Das fehlt noch. Ist diese Option dabei, spart man sich Anpassungen auf ältere Instanzen, da Curl dann die Weiterleitungen nutzt.

**Comment by skerbis** [comment]
@tbaddade Danke, das habe ich übersehen: https://github.com/FriendsOfREDAXO/osmproxy/commit/aaeef85699a1aed425afd3f00d9c8948a40e2319

**Comment by tbaddade** [comment]
Danke dir

**Comment by skerbis** [comment]
Danke Dir
