### ISSUE TITLE
HTTP_REFERER ist nicht immer gesetzt

### ISSUE THREAD

**Issue by tbaddade** [FriendsOfREDAXO/osmproxy#7]
Es geht um diese Zeile

https://github.com/FriendsOfREDAXO/osmproxy/blob/master/boot.php#L3

Dadurch kann es passieren, dass der Code zuvor abbricht und die Fliesen nicht geladen werden.

**Comment by skerbis** [comment]
Was wäre die Alternative?

**Comment by skerbis** [comment]
@tbaddade Hast du eine Vorschlag was ich sonst machen kann um zu vermeiden, dass fremde Server den Proxy missbrauchen?

**Comment by tbaddade** [comment]
@staabm Siehst du hier Möglichkeiten wie man das sinnvoller umsetzen kann?

**Comment by staabm** [comment]
was ist das ziel dieses codes? 

reicht es nicht einfach nur statt
```php
if (parse_url($_SERVER['HTTP_REFERER'], PHP_URL_HOST) != $_SERVER['SERVER_NAME'] && !rex_backend_login::hasSession())
```

es so zu machen?

```php
if (!rex_backend_login::hasSession())
```

**Comment by skerbis** [comment]
Ich möchte vermeiden, dass fremde Referrer die den Proxy verwenden. Eigentlich hat if (!rex_backend_login::hasSession())  keinen Sinn.

**Comment by staabm** [comment]
um fremde urls auszuschließen ist der Referer nicht verlässlich.
der wird nicht von jedem browser geschickt, daher geht das so nicht.

du könntest z.b. nen csrf token o.ä. verwenden (oder du musst bewusst zulassen, dass wenn kein http-referer gesendet wird, es trotzdem erlaubt ist).

hat das sicherheitsaspekte oder aus welcher motivation heraus soll man das nicht von fremden urls aus können? (hab den code nicht durchdrungen)

**Comment by skerbis** [comment]
Der Proxy legt einen Cache ab. Wenn eine fremde Seite diesen Proxy verwenden würde, könnte die diesen Cache "zumüllen" oder gar den Webspace sprengen. Die OSM-Tiles sollten nur von der eigentlichen Seite verwendet werden.

**Comment by skerbis** [comment]
Eine Alternative wäre wohl bei missing Referrer die Tiles nicht zu cachen sondern durchzuschleifen?  Das habe ich anfangs mal gemacht. Sorgte aber für einen langsamen Aufbau.

**Comment by staabm** [comment]
ich denke am einfachsten wäre dass dann mittels einer http session und csrf token.
@gharlan hast du noch eine andere idee?

vllt probierst du das mal.

**Comment by skerbis** [comment]
gut beim csrf brauche ich Hilfe. Das Konzept verstehe ich noch nicht.

**Comment by skerbis** [comment]
ich warte mal ab wie es @staabm hier löst: https://github.com/FriendsOfREDAXO/experimental/tree/master/plugins/proxy

ggf. könnte dieses AddOn dann auch wegfallen oder den neuen Proxy nutzen.

**Comment by skerbis** [comment]
@tbaddade 
Schau mal, ich habe jetzt einen empty REFERRER zugelassen. Löst das Dein Problem?
So grenze ich jetzt zumindest die REFERRER aus, die eine andere Domain haben. Ich denke das ist ein Kompromiss mit dem ich leben kann.

**Comment by tbaddade** [comment]
So richtig ist damit dein Problem nicht gelöst. Zumindest willst du einen Schutz haben, der aber nur bei gesetzten REFERRER funktioniert. Ich würde da vermutlich keinen Unterschied machen. Mal sehen wie @staabm das bei dem Proxy PlugIn umsetzt.

Weshalb sollen keine Fliesen erzeugt werden, sobald man im Backend ausgeloggt ist? Was magst du damit bezwecken?

**Comment by skerbis** [comment]
Das mit dem Login hatte ich noch übersehen und ist raus. In der jetzigen Fassung hier bei GitHub liefert er keine Kacheln sollte der Referrer != der Website-Domain sein. Es liefert aber Kacheln ist der REFERRER leer. In welchen Fällen ist denn der Referrer überhaupt leer?  In Browsern kann ich es nicht reproduzieren.  Der Normalfall ist doch, dass die Kacheln per JS (z.B. Leaflet) oder Verlinkung aufgerufen werden. Dann sollte doch ein Referrer da sein.

**Comment by skerbis** [comment]
@tbaddade @staabm @gharlan 

Ich würde gerne den Weg über csrf gehen. Kann mir jemand die Anwendung erklären?
Wie ich den Token generiere weiß ich bereits. 

$csrfToken = rex_csrf_token::factory('osmcheck');
und den token holen auch rex_csrf_token::factory('osmcheck')->getValue();
Gut. 
Wie muss der Parameter an der Url aussehen?

Nur ?csrf=TOKENDINGS ... oder muss die der Key auch rein?

**Comment by staabm** [comment]
Meinst du das?
https://github.com/redaxo/redaxo/blob/6ec54285af3ff7006ceba4e8b00d026a17ba8213/redaxo/src/core/lib/csrf_token.php#L74

**Comment by skerbis** [comment]
Danke, das war's

**Comment by skerbis** [comment]
bringt nichts, da sich die url ändert und der browser cache nicht greifen kann
